resources:
  repositories:
    - repository: templates
      type: github
      endpoint: github
      name: ccdc-opensource/conan-azure-devops
      ref: refs/heads/development

extends:
  template: third-party-library-all-platforms-from-conan-center.yml@templates
  parameters:
    package: libpng
    package_version: 1.6.40
    source_repository: public-conan-center
    destination_repository: ccdc-3rdparty-conan
    use_release_zlib_profile: True
